### ISSUE TITLE
部分区域无法通过认证

### ISSUE THREAD

**Issue by jimlee2048** [jimlee2048/minieap-gdufs#1]
根据使用反馈，本项目在部分区域无法成功通过认证。

表现为输出 `字段格式错误，未发现特征值（偏移量 0x6）`，初步分析是由于minieap无法适应这些区域所需的特殊结构认证包。

问题详见 https://github.com/updateing/minieap/issues/67#issue-1148427271

已知的不可用区域：
- 南校区
  - 南苑13栋
  - 友苑B栋

如果您在别的区域使用本项目时遇到了同样的问题，欢迎在本issue补充。

**Comment by jimlee2048** [comment]
可能的解决办法：修改minieap组装认证数据包的相关代码，使其适配这些区域的特殊结构认证包。（需要另起分支）

由于我个人能力不足（不懂C），无法展开进一步的修改。如果您对此感兴趣，欢迎在本issue留言并留下邮箱（为保护隐私请先使用base64编码），我可以提供我已有的全部相关资料，并愿意提供尽可能的协助。

**Comment by FrenkyOHOHOH** [comment]
你好，我是现在住在南苑13的在校生，我想对比一下十二、十三栋的包有什么区别，能看一下12栋linux下认证抓包的pcap文件吗，想看一下eap-request包有没有区别，我的邮箱是ZnJlbmt5eHkwMjQ2QGdtYWlsLmNvbQ==，如果看到可以回复一下，谢谢

**Comment by jimlee2048** [comment]
截至 2022-08-22，该问题仍未修复，欢迎任何感兴趣的朋友fork本项目，需要任何协助请随时开issue！

**Comment by Lupus14** [comment]
请问友苑B栋可以使用这个minieap的openwrt插件嘛？试了一下也显示了类似https://github.com/updateing/minieap/issues/67#issue-1148427271的问题

**Comment by jimlee2048** [comment]
> 请问友苑B栋可以使用这个minieap的openwrt插件嘛？试了一下也显示了类似[https://github.com/updateing/minieap/issues/67#issue-1148427271的问题](https://github.com/updateing/minieap/issues/67#issue-1148427271%E7%9A%84%E9%97%AE%E9%A2%98)

我没在友苑测试过，抱歉。

如果是OpenWRT下使用，请问能确定安装的是我修改过的版本吗？

请参考 https://github.com/jimlee2002/minieap-gdufs/issues/2#issuecomment-1079934302

**Comment by Lupus14** [comment]
确实通过SDK编译并成功安装openwrt-minieap-gdufs到路由器中，接口选项可以添加eap的接口；今天在友苑尝试用该插件进行锐捷认证，发现除了fake-serial的问题外，还存在该问题：【D】字段格式错误，未发现特征值（偏移量0x6）

**Comment by jimlee2048** [comment]
> 确实通过SDK编译并成功安装openwrt-minieap-gdufs到路由器中，接口选项可以添加eap的接口；今天在友苑尝试用该插件进行锐捷认证，发现除了fake-serial的问题外，还存在该问题：【D】字段格式错误，未发现特征值（偏移量0x6）

那很可能就是和南苑13栋一样不能用的情况了。
请问是南校区的友苑B栋吗？

**Comment by Lupus14** [comment]
是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决

**Comment by jimlee2048** [comment]
> 是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决

fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。

已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。

如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。

**Comment by Lupus14** [comment]
想问一下大佬哪里有抓包相关的教程？非计科专业小白，不会抓包，只知道可以用Wireshark来抓包；另外想问一下大佬，能否通过路由器的无线中继功能，对GDUFS_AUTO进行中继？

**Comment by jimlee2048** [comment]
> 想问一下大佬哪里有抓包相关的教程？非计科专业小白，不会抓包，只知道可以用Wireshark来抓包；

以下是我研究锐捷认证时用到的一些重要资料，希望能对你的研究有帮助：
-  [Mentohust V4版本的心得](https://github.com/rensilin/mentohust_nwafu/blob/master/README.md)，作者为@ShanQincheng，简单介绍了如何使用 Wireshark 进行抓包与分析（这里是该文于[@rensilin](https://github.com/rensilin)/[mentohust_nwafu](https://github.com/rensilin/mentohust_nwafu)上的无图片存档，原文链接已失效）
-	[锐捷认证过程分析与第三方锐捷认证客户端的设计与实现.pdf](https://github.com/ShanQincheng/jmuSupplicant/blob/master/doc/%E9%94%90%E6%8D%B7%E8%AE%A4%E8%AF%81%E8%BF%87%E7%A8%8B%E5%88%86%E6%9E%90%E4%B8%8E%E7%AC%AC%E4%B8%89%E6%96%B9%E9%94%90%E6%8D%B7%E8%AE%A4%E8%AF%81%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%9A%84%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0.pdf)，解释了锐捷认证的原理与认证包的通用结构
-	[我校锐捷使用该V4算法，应该是丢失了许多信息，导致无法连接 #282](https://github.com/hyrathb/mentohust/issues/282)，内含checkv4中数组的提取方法
-	[关于中文服务类型以及版本号字符串的确认以及参数处理 #40](https://github.com/updateing/minieap/issues/40)，介绍了认证包中各种认证字段的解析提取

> 另外想问一下大佬，能否通过路由器的无线中继功能，对GDUFS_AUTO进行中继？

我没有尝试过，你可以试试看。
你可能会对这篇前辈的文章感兴趣：[广外校园网使用指北（大聪明版）- 是你猫兄啊](https://mp.weixin.qq.com/s/TzFLEV2xrQXJh5Fh14zzxQ)

**Comment by Yukira252** [comment]
> > 是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决
> 
> fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。
> 
> 已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。
> 
> 如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。

你好 来自北校的问候
我已经找到了有关“【D】字段格式错误，未发现特征值（偏移量0x6）”的解决方法
我在WAN口没有使用静态地址并且没有复制成功验证之网卡的MAC地址的情况下 复现了这一问题
在WAN接口使用静态地址填入分配的IP、网关等信息并复制MAC到WAN口后
路由器成功通过您的插件进行了独立的锐捷认证 达成校园网接入路由器 路由器通过校园网上网
路由器为红米AC2100 刷入OPEN WRT系统后 通过编译将您编写的插件转换成该路由器能够使用的安装文件 并装入路由器
后经过上述提到过的操作实现了网络共享
目前在舍内的使用一切顺利 感谢大佬您的努力付出 若有其他想要咨询的可以再向我咨询
再次衷心感谢大佬

**Comment by jimlee2048** [comment]
> > > 是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决
> > 
> > 
> > fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。
> > 已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。
> > 如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。
> 
> 你好 来自北校的问候 我已经找到了有关“【D】字段格式错误，未发现特征值（偏移量0x6）”的解决方法 我在WAN口没有使用静态地址并且没有复制成功验证之网卡的MAC地址的情况下 复现了这一问题 在WAN接口使用静态地址填入分配的IP、网关等信息并复制MAC到WAN口后 路由器成功通过您的插件进行了独立的锐捷认证 达成校园网接入路由器 路由器通过校园网上网 路由器为红米AC2100 刷入OPEN WRT系统后 通过编译将您编写的插件转换成该路由器能够使用的安装文件 并装入路由器 后经过上述提到过的操作实现了网络共享 目前在舍内的使用一切顺利 感谢大佬您的努力付出 若有其他想要咨询的可以再向我咨询 再次衷心感谢大佬

🎉 @Yukira252, Congratulation! 很高兴听到你成功解决问题通过认证，也非常感谢你愿意分享宝贵的解决方法！可惜我已无法亲自对该方法进行更多的适用性验证。

❤️ 看到这里的其他朋友，如果这条解决方法对你有帮助，欢迎在这里留言告诉我们！

在有更多的成功反馈前，我将保持该 issue 为 open 状态。

**Comment by jyc27** [comment]
> > > 是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决
> > 
> > fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。
> > 
> > 已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。
> > 
> > 如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。
> 
> 你好 来自北校的问候
> 我已经找到了有关“【D】字段格式错误，未发现特征值（偏移量0x6）”的解决方法
> 我在WAN口没有使用静态地址并且没有复制成功验证之网卡的MAC地址的情况下 复现了这一问题
> 在WAN接口使用静态地址填入分配的IP、网关等信息并复制MAC到WAN口后
> 路由器成功通过您的插件进行了独立的锐捷认证 达成校园网接入路由器 路由器通过校园网上网
> 路由器为红米AC2100 刷入OPEN WRT系统后 通过编译将您编写的插件转换成该路由器能够使用的安装文件 并装入路由器
> 后经过上述提到过的操作实现了网络共享
> 目前在舍内的使用一切顺利 感谢大佬您的努力付出 若有其他想要咨询的可以再向我咨询
> 再次衷心感谢大佬

同学您好，我日前同样购入了红米ac2100 并刷入了openwrt，但在编译ipk文件的操作上出现了一些问题，可以指导一下或是发送您编译好的文件给我吗@Yukira252

**Comment by Yukira252** [comment]
> > > > 是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决
> > > 
> > > 
> > > fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。
> > > 已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。
> > > 如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。
> > 
> > 
> > 你好 来自北校的问候
> > 我已经找到了有关“【D】字段格式错误，未发现特征值（偏移量0x6）”的解决方法
> > 我在WAN口没有使用静态地址并且没有复制成功验证之网卡的MAC地址的情况下 复现了这一问题
> > 在WAN接口使用静态地址填入分配的IP、网关等信息并复制MAC到WAN口后
> > 路由器成功通过您的插件进行了独立的锐捷认证 达成校园网接入路由器 路由器通过校园网上网
> > 路由器为红米AC2100 刷入OPEN WRT系统后 通过编译将您编写的插件转换成该路由器能够使用的安装文件 并装入路由器
> > 后经过上述提到过的操作实现了网络共享
> > 目前在舍内的使用一切顺利 感谢大佬您的努力付出 若有其他想要咨询的可以再向我咨询
> > 再次衷心感谢大佬
> 
> @Yukira252 同学您好，我日前同样购入了红米ac2100 并刷入了openwrt，但在编译ipk文件的操作上出现了一些问题，可以指导一下或是发送您编译好的文件给我吗（anljMjdAZm94bWFpbC5jb20=这是我的邮箱（base64）

[minieap-gdufs_0.93-5_mipsel_24kc.zip](https://github.com/user-attachments/files/17516864/minieap-gdufs_0.93-5_mipsel_24kc.zip)
这是编译好的插件 你可以尝试一下

**Comment by jyc27** [comment]
非常感谢，因为脚手架不稳定的缘故 我在搭建编译环境的时候一直出错，等下下课后回去继续尝试，再次感谢！（我也是北校的）



---Original---
From: ***@***.***&gt;
Sent at: 2024年10月25日(Fri) PM2:06
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jimlee2048/minieap-gdufs] 部分区域无法通过认证 (Issue #1)




     
是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决
  
fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。
 已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。
 如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。
  
你好 来自北校的问候
 我已经找到了有关“【D】字段格式错误，未发现特征值（偏移量0x6）”的解决方法
 我在WAN口没有使用静态地址并且没有复制成功验证之网卡的MAC地址的情况下 复现了这一问题
 在WAN接口使用静态地址填入分配的IP、网关等信息并复制MAC到WAN口后
 路由器成功通过您的插件进行了独立的锐捷认证 达成校园网接入路由器 路由器通过校园网上网
 路由器为红米AC2100 刷入OPEN WRT系统后 通过编译将您编写的插件转换成该路由器能够使用的安装文件 并装入路由器
 后经过上述提到过的操作实现了网络共享
 目前在舍内的使用一切顺利 感谢大佬您的努力付出 若有其他想要咨询的可以再向我咨询
 再次衷心感谢大佬
  
@Yukira252 同学您好，我日前同样购入了红米ac2100 并刷入了openwrt，但在编译ipk文件的操作上出现了一些问题，可以指导一下或是发送您编译好的文件给我吗（anljMjdAZm94bWFpbC5jb20=这是我的邮箱（base64）
  
minieap-gdufs_0.93-5_mipsel_24kc.zip
 这是编译好的插件 你可以尝试一下

**Comment by jyc27** [comment]
> > > > > 是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决
> > > > 
> > > > 
> > > > fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。
> > > > 已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。
> > > > 如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。
> > > 
> > > 
> > > 你好 来自北校的问候
> > > 我已经找到了有关“【D】字段格式错误，未发现特征值（偏移量0x6）”的解决方法
> > > 我在WAN口没有使用静态地址并且没有复制成功验证之网卡的MAC地址的情况下 复现了这一问题
> > > 在WAN接口使用静态地址填入分配的IP、网关等信息并复制MAC到WAN口后
> > > 路由器成功通过您的插件进行了独立的锐捷认证 达成校园网接入路由器 路由器通过校园网上网
> > > 路由器为红米AC2100 刷入OPEN WRT系统后 通过编译将您编写的插件转换成该路由器能够使用的安装文件 并装入路由器
> > > 后经过上述提到过的操作实现了网络共享
> > > 目前在舍内的使用一切顺利 感谢大佬您的努力付出 若有其他想要咨询的可以再向我咨询
> > > 再次衷心感谢大佬
> > 
> > 
> > @Yukira252 同学您好，我日前同样购入了红米ac2100 并刷入了openwrt，但在编译ipk文件的操作上出现了一些问题，可以指导一下或是发送您编译好的文件给我吗（anljMjdAZm94bWFpbC5jb20=这是我的邮箱（base64）
> 
> [minieap-gdufs_0.93-5_mipsel_24kc.zip](https://github.com/user-attachments/files/17516864/minieap-gdufs_0.93-5_mipsel_24kc.zip) 这是编译好的插件 你可以尝试一下

在安装了@Yukira252 适配红米ac2100的ipk软件包至openwrt并按照指引设置后，路由器直接达成了锐捷认证，没有出现“【D】字段格式错误，未发现特征值（偏移量0x6）”的问题，坐标北校，目前使用一切正常。非常感谢诸位大佬的分享和 @Yukira252 提供的编译后文件！

**Comment by Yukira252** [comment]
> > > > > > 是的，不过我还是想晚点回校再试一次看看行不行，后来添加了虚假硬盘编号，没有出现【W】fake-serial的问题；不过我也不懂C语言，这个问题恐怕也无法解决
> > > > > 
> > > > > 
> > > > > fake-serial 相关的错误提示不用管，也不用设置，因为GDUFS并不校验该字段。
> > > > > 已将友苑B栋备注到已知的不可用区域中，感谢您的尝试。有任何最新动向也可以随时在本issue联系。
> > > > > 如果有任何朋友对解决该问题感兴趣，或者是在已知不可用区域通过了认证，欢迎您在本issue留言，谢谢。
> > > > 
> > > > 
> > > > 你好 来自北校的问候
> > > > 我已经找到了有关“【D】字段格式错误，未发现特征值（偏移量0x6）”的解决方法
> > > > 我在WAN口没有使用静态地址并且没有复制成功验证之网卡的MAC地址的情况下 复现了这一问题
> > > > 在WAN接口使用静态地址填入分配的IP、网关等信息并复制MAC到WAN口后
> > > > 路由器成功通过您的插件进行了独立的锐捷认证 达成校园网接入路由器 路由器通过校园网上网
> > > > 路由器为红米AC2100 刷入OPEN WRT系统后 通过编译将您编写的插件转换成该路由器能够使用的安装文件 并装入路由器
> > > > 后经过上述提到过的操作实现了网络共享
> > > > 目前在舍内的使用一切顺利 感谢大佬您的努力付出 若有其他想要咨询的可以再向我咨询
> > > > 再次衷心感谢大佬
> > > 
> > > 
> > > @Yukira252 同学您好，我日前同样购入了红米ac2100 并刷入了openwrt，但在编译ipk文件的操作上出现了一些问题，可以指导一下或是发送您编译好的文件给我吗（anljMjdAZm94bWFpbC5jb20=这是我的邮箱（base64）
> > 
> > 
> > [minieap-gdufs_0.93-5_mipsel_24kc.zip](https://github.com/user-attachments/files/17516864/minieap-gdufs_0.93-5_mipsel_24kc.zip) 这是编译好的插件 你可以尝试一下
> 
> 在安装了@Yukira252 适配红米ac2100的ipk软件包至openwrt并按照指引设置后，路由器直接达成了锐捷认证，没有出现“【D】字段格式错误，未发现特征值（偏移量0x6）”的问题，坐标北校，目前使用一切正常。非常感谢诸位大佬的分享和 @Yukira252 提供的编译后文件！

恭喜恭喜！我也是蹭了前人的树 才乘了现在的凉 这个编译好的插件来自@miaoermua大佬 多亏两位大佬的付出！对了 记得不要到处招摇炫耀哦 毕竟这并不是见得了光的事情）低调使用就好！
