### ISSUE TITLE
服务器通知输出乱码，无法通过验证

### ISSUE THREAD

**Issue by babattata-ta** [jimlee2048/minieap-gdufs#2]
MiniEAP 0.93
Hamster Tian, 2016

[2022/3/17 20:51:30][I] 
RJv3 for MiniEAP 0.93
V3 校验算法来自 hyrathb@GitHub
Hamster Tian, 2016

[2022/3/17 20:51:30][I] ========================
[2022/3/17 20:51:30][I] MiniEAP 0.93已启动
[2022/3/17 20:51:30][I] 正在查找认证服务器
[2022/3/17 20:51:30][I] 正在回应用户名请求
[2022/3/17 20:51:30][I] 正在回应密码请求
[2022/3/17 20:51:30][I] 服务器通知：
[2022/3/17 20:51:30][I] 用户不允许使用本服务!Q|??gk?S
[2022/3/17 20:51:30][W] 认证失败 1 次，将在 30 秒或服务器请求后重试……
[2022/3/17 20:51:33][I] 正在回应用户名请求
[2022/3/17 20:51:38][I] 正在回应用户名请求
[2022/3/17 20:51:40][I] 正在回应用户名请求
[2022/3/17 20:51:40][I] 服务器通知：
[2022/3/17 20:51:40][I] 0/36 
[2022/3/17 20:51:40][W] 认证失败 2 次，将在 30 秒或服务器请求后重试……
[2022/3/17 20:51:40][I] 正在回应密码请求
[2022/3/17 20:51:40][I] 服务器通知：
[2022/3/17 20:51:40][I] 用户不允许使用本服务!?],忄?绎
[2022/3/17 20:51:40][E] 认证失败 3 次，已达到指定次数，正在退出……
[2022/3/17 20:51:40][I] MiniEAP 已退出
root@ImmortalWrt:~# 

log如上，请求大佬帮助

**Comment by babattata-ta** [comment]
抱歉，提错项目了。应该是openwrt那边的项目

**Comment by jimlee2048** [comment]
没事，issue开这里没问题
请问你是在北校区使用嘛？

**Comment by jimlee2048** [comment]
另外，友情提示一下，本项目面向GDUFS而不是GDUF

**Comment by babattata-ta** [comment]
是GDUFS，之前我在校园的actions也受大佬照顾了
是南校区

**Comment by jimlee2048** [comment]
请问使用的是 https://github.com/jimlee2002/openwrt-minieap-gdufs 嘛？
尝试手动指定下服务名为`default`？
![image](https://user-images.githubusercontent.com/21117946/160278242-c11e5857-3ab9-4ca5-a2ba-dfff8231247d.png)

**Comment by babattata-ta** [comment]
是的。但是不知道为什么GUI连不上minieap，右边的log是空的，上面的日志是我在Xshell上操作的。

**Comment by jimlee2048** [comment]
openwrt上使用的简易指南
- 安装/编译时添加 [openwrt-minieap-gdufs](https://github.com/jimlee2002/openwrt-minieap-gdufs) 与 [luci-proto-minieap](https://github.com/ysc3839/luci-proto-minieap)
- 前往Openwrt管理面板，在网络设置中新建接口，协议选择`MiniEAP 客户端`，名字随意（下以eap为例）
- 进入新建的接口`eap`，配置以下参数
    - 基本信息中，填写用户名与密码，数据包插件选择rjv3
    - rjv3插件设置中，EAP广播地址选择`锐捷私有`，DHCP认证选择`二次认证`，其他选项留空即可（已配置默认参数）
    - 接口物理设置中，选择wan口所在的以太网适配器

保存后就可以试着手动连接一下接口，然后去内核日志里看详细日志能不能认证上

**Comment by babattata-ta** [comment]
使用shell尝试minieap -u 用户名 -p 密码 -n wan --module rjv3 --fake-serial FWU672GY —server defaul
输出以下日志

MiniEAP 0.93
Hamster Tian, 2016

[2022/3/17 21:43:26][I] 
RJv3 for MiniEAP 0.93
V3 校验算法来自 hyrathb@GitHub
Hamster Tian, 2016

[2022/3/17 21:43:26][I] ========================
[2022/3/17 21:43:26][I] MiniEAP 0.93已启动
[2022/3/17 21:43:26][I] 正在查找认证服务器
[2022/3/17 21:43:26][I] 正在回应用户名请求
[2022/3/17 21:43:26][I] 正在回应密码请求
[2022/3/17 21:43:27][I] 服务器通知：
[2022/3/17 21:43:27][I] 用户不允许使用本服务!ォ?w??坟
[2022/3/17 21:43:27][W] 认证失败 1 次，将在 30 秒或服务器请求后重试……
[2022/3/17 21:43:34][I] 正在回应用户名请求
[2022/3/17 21:43:36][I] 正在回应用户名请求
[2022/3/17 21:43:36][I] 服务器通知：
[2022/3/17 21:43:36][I] 0/31 
[2022/3/17 21:43:36][W] 认证失败 2 次，将在 30 秒或服务器请求后重试……
[2022/3/17 21:43:36][I] 正在回应密码请求
[2022/3/17 21:43:36][I] 服务器通知：
[2022/3/17 21:43:36][I] 用户不允许使用本服务!#l梭??{5掣
[2022/3/17 21:43:36][E] 认证失败 3 次，已达到指定次数，正在退出……
[2022/3/17 21:43:36][I] MiniEAP 已退出
root@ImmortalWrt:~#

**Comment by babattata-ta** [comment]
我先尝试大佬的教程

**Comment by jimlee2048** [comment]
> openwrt上使用的简易指南
> 
> * 安装/编译时添加 [openwrt-minieap-gdufs](https://github.com/jimlee2002/openwrt-minieap-gdufs) 与 [luci-proto-minieap](https://github.com/ysc3839/luci-proto-minieap)
> * 前往Openwrt管理面板，在网络设置中新建接口，协议选择`MiniEAP 客户端`，名字随意（下以eap为例）
> * 进入新建的接口`eap`，配置以下参数
>   
>   * 基本信息中，填写用户名与密码，数据包插件选择rjv3
>   * rjv3插件设置中，EAP广播地址选择`锐捷私有`，DHCP认证选择`二次认证`，其他选项留空即可（已配置默认参数）
>   * 接口物理设置中，选择wan口所在的以太网适配器
> 
> 保存后就可以试着手动连接一下接口，然后去内核日志里看详细日志能不能认证上

如能成功，下面是一些后续使用的建议：
- 添加计划任务，每天早上自动重新认证（夜间断网会强制踢出认证）
  ```
  30 5 * * * ifup eap
  ```
  解释：每天早上5点30重启接口`eap`，重新触发认证。我校 5 AM 左右恢复认证，请根据自己需要调整
- 关闭ipv6相关的东西。我校虽然能分配到ipv6地址但实际上完全不可用，如果路由上开启了ipv6相关的支持还会影响部分应用的网络链接（优先走ipv6，然而我校ipv6连不上），总之就当我校ipv6不存在吧……

**Comment by babattata-ta** [comment]
您好：
![image](https://user-images.githubusercontent.com/84716066/160279449-462c2cd4-6a4d-46ca-868a-c0d9e6e750be.png)
如图所示，没有“MiniEAP 客户端”
能确认编译时已经添加了openwrt-minieap-gdufs与luci-proto-minieap
其他一起添加的有UA2F等反检测工具

补充：路由器是红米AC2100

**Comment by jimlee2048** [comment]
> 

如果编译时勾选了`luci-proto-minieap`，这里应该就能出现MiniEAP 客户端的选项，请你再次确认一下是否已安装`luci-proto-minieap`

**Comment by babattata-ta** [comment]
我正在尝试重新编译，请问大佬是怎样做反检测的
知道学校是用什么检测多设备的吗？

**Comment by jimlee2048** [comment]
> 我正在尝试重新编译，请问大佬是怎样做反检测的 知道学校是用什么检测多设备的

我没有做任何的反检测处理。据我的使用观察来看，我校的检测并不严格，或者说根本没开检测，只是限制同时在线的认证客户端数量。
总之不要乱配置路由参数，在学校内网搭服务什么的，低调使用就是了。

**Comment by babattata-ta** [comment]
大佬您好：
认证失败，log如下
```MiniEAP 0.93
Hamster Tian, 2016

[2022/3/17 20:20:04][I] 
RJv3 for MiniEAP 0.93
V3 校验算法来自 hyrathb@GitHub
Hamster Tian, 2016

[2022/3/17 20:20:04][I] ========================
[2022/3/17 20:20:04][I] MiniEAP 0.93已启动
[2022/3/17 20:20:04][I] 正在查找认证服务器
[2022/3/17 20:20:04][I] 正在回应用户名请求
[2022/3/17 20:20:04][I] 正在回应密码请求
[2022/3/17 20:20:04][I] 服务器通知：
[2022/3/17 20:20:04][I] 用户不允许使用本服务!I3??)?|?
[2022/3/17 20:20:04][W] 认证失败 1 次，将在 30 秒或服务器请求后重试……
[2022/3/17 20:20:13][I] 正在回应用户名请求
[2022/3/17 20:20:14][I] 正在回应用户名请求
[2022/3/17 20:20:14][I] 服务器通知：
[2022/3/17 20:20:14][I] 喋?
??il闪???
[2022/3/17 20:20:14][W] 认证失败 2 次，将在 30 秒或服务器请求后重试……
[2022/3/17 20:20:14][I] 正在回应密码请求
[2022/3/17 20:20:14][I] 服务器通知：
[2022/3/17 20:20:14][I] 用户不允许使用本服务!?陋o??
[2022/3/17 20:20:14][E] 认证失败 3 次，已达到指定次数，正在退出……
[2022/3/17 20:20:14][I] MiniEAP 已退出
root@ImmortalWrt:~# 
```
确实少了个`luci-proto-minieap`，重新编译后有协议是有了，但是还是认证失败

请求帮助

**Comment by jimlee2048** [comment]
> 

![image](https://user-images.githubusercontent.com/21117946/160281816-2edbeec2-6413-46ac-9c6e-204864b89852.png)
这里的服务名留空试试？我默认设置为`default`了

**Comment by cyugwan** [comment]
请问有没有可能像这个issues一样要开通Linux权限
https://github.com/Dark-Existed/MentoHUST-FZU-OpenWrt/issues/2

**Comment by babattata-ta** [comment]
```
Q: 服务器通知“请查看您的套餐是否正常。”“用户不能使用该服务！”等类似信息是什么原因？要如何解决？
A: 出现这种提示，大多数哦情况下代表您的学校是可以使用minieap的，但是服务接口不同，所以被禁止服务。minieap使用的是大多数锐捷认证高校的默认服务接口“internet”。
解决方法：找到学校的自助服务中心，在自助服务中心中找到类似“上网管理”“上网明细”类似字样，在弹出的列表中找到服务栏，表格中的内容即为服务接口名称，例如unicom、internet等，在命令中添加--service 服务接口名称 重新认证即可
```
有什么方法可以得到学校的服务名称呢
恩山有一篇教程说如是说，应该是服务名称出了问题

**Comment by jimlee2048** [comment]
> ```
> Q: 服务器通知“请查看您的套餐是否正常。”“用户不能使用该服务！”等类似信息是什么原因？要如何解决？
> A: 出现这种提示，大多数哦情况下代表您的学校是可以使用minieap的，但是服务接口不同，所以被禁止服务。minieap使用的是大多数锐捷认证高校的默认服务接口“internet”。
> 解决方法：找到学校的自助服务中心，在自助服务中心中找到类似“上网管理”“上网明细”类似字样，在弹出的列表中找到服务栏，表格中的内容即为服务接口名称，例如unicom、internet等，在命令中添加--service 服务接口名称 重新认证即可
> ```
> 
> 有什么方法可以得到学校的服务名称呢 恩山有一篇教程说如是说，应该是服务名称出了问题

目前默认用的这个`default`我是从官方Linux客户端认证的抓包结果中获得的，按理来说全校的服务名都是统一的，你可以试着用wireshark抓一下官方客户端认证时发送的包，或者我记得windows锐捷客户端下认证后也能看到。

**Comment by jimlee2048** [comment]
一个猜测：你可能是因为当前认证设备数量达到了设备上限（2个），所以无法认证，试着手机上先取消链接一下学校wifi？

**Comment by babattata-ta** [comment]
```[2022/3/17 21:18:31][I] 
RJv3 for MiniEAP 0.93
V3 校验算法来自 hyrathb@GitHub
Hamster Tian, 2016

[2022/3/17 21:18:31][I] ========================
[2022/3/17 21:18:31][I] MiniEAP 0.93已启动
[2022/3/17 21:18:31][I] 正在查找认证服务器
[2022/3/17 21:18:31][I] 正在回应用户名请求
[2022/3/17 21:18:31][I] 正在回应密码请求
[2022/3/17 21:18:31][I] 服务器通知：
[2022/3/17 21:18:31][I] 使用了非管理员指定的客户端!Z?O拓
[2022/3/17 21:18:31][W] 认证失败 1 次，将在 30 秒或服务器请求后重试……
[2022/3/17 21:18:41][I] 正在回应用户名请求
[2022/3/17 21:18:41][I] 服务器通知：
[2022/3/17 21:18:41][I] 
                        ?B
桕S轂]c
 
[2022/3/17 21:18:41][W] 认证失败 2 次，将在 30 秒或服务器请求后重试……
[2022/3/17 21:18:43][I] 正在回应用户名请求
[2022/3/17 21:18:43][I] 正在回应密码请求
[2022/3/17 21:18:43][I] 服务器通知：
[2022/3/17 21:18:43][I] 使用了非管理员指定的客户端!_榈o(
[2022/3/17 21:18:43][E] 认证失败 3 次，已达到指定次数，正在退出……
[2022/3/17 21:18:43][I] MiniEAP 已退出
root@ImmortalWrt:~# 
```
shell尝试了一下
`minieap -u 用户名 -p 密码 -n wan --module rjv3 --fake-serial FWU672GY --service default --dhcp-type 1`
尝试了一下，log变如上，是minieap被禁了吗

**Comment by jimlee2048** [comment]
> 

请问你确定自己编译时添加的是[openwrt-minieap-gdufs](https://github.com/jimlee2002/openwrt-minieap-gdufs)，而非ImmortalWrt默认源中提供的原版openwrt-minieap吗？

查看当前安装的名称包含minieap的软件包：
```
opkg list | minieap
```
如果你添加的是我改好的[openwrt-minieap-gdufs](https://github.com/jimlee2002/openwrt-minieap-gdufs)，那么输出的结果中应该包含一个`minieap-gdufs`而不是`minieap`

**Comment by jimlee2048** [comment]
如果你不知道如何在编译时使用我的修改版本：
首先，先挂载到openwrt文件夹下
随后，克隆我改好的openwrt-minieap-gdufs
```
 git clone https://github.com/jimlee2002/openwrt-minieap-gdufs.git package/network/minieap-gdufs
```
随后进入`menuconfig`，在`Network`里取消勾选原版`minieap`，同时勾上`minieap-gdufs`
```
make menuconfig
```

**Comment by babattata-ta** [comment]
大佬您好：
shell输入
`minieap -u 用户名 -p 密码 -n wan --module rjv3 --fake-serial FWU672GY --service default`
后输出日志验证成功
```
MiniEAP 0.93
Hamster Tian, 2016

[E] 无法打开配置文件: No such file or directory (2)
[W] 配置文件解析出错，请注意命令行参数是否完整
[I] 
RJv3 for MiniEAP 0.93
V3 校验算法来自 hyrathb@GitHub
Hamster Tian, 2016

[I] ========================
[I] MiniEAP 0.93已启动
[I] 正在查找认证服务器
[I] 正在回应用户名请求
[I] 正在回应密码请求
[I] 首次认证成功，正在执行 DHCP 脚本以准备第二次认证
[E] IPv4 地址获取错误
[W] DHCP 可能尚未完成，将继续等待……
[I] 认证成功
[I] DHCP 完成，正在开始第二次认证
[I] 正在查找认证服务器
[I] 正在回应用户名请求
[I] 正在回应密码请求
[I] 二次认证成功
[I] 服务器通知：
[I] 欢迎使用广外大网络！
[I] 计费通知：
[I] 您当前使用的服务为default;
账户余额为0.00元;
计费策略为学生包半年;
[I] 正定时发送 Keep-Alive 报文以保持在线……
[I] 认证成功
```
但是在网络——接口处用`miniEAP客户端`处验证会显示
`Sun Mar 27 15:18:06 2022 daemon.notice netifd: wan (4844): minieap: Missing username or password.`
我再检查下自己编译有没问题

**Comment by jimlee2048** [comment]
> 
> 大佬您好：
> shell输入
> `minieap -u 用户名 -p 密码 -n wan --module rjv3 --fake-serial FWU672GY --service default`
> 后输出日志验证成功
> ```
> MiniEAP 0.93
> Hamster Tian, 2016
> 
> [E] 无法打开配置文件: No such file or directory (2)
> [W] 配置文件解析出错，请注意命令行参数是否完整
> [I] 
> RJv3 for MiniEAP 0.93
> V3 校验算法来自 hyrathb@GitHub
> Hamster Tian, 2016
> 
> [I] ========================
> [I] MiniEAP 0.93已启动
> [I] 正在查找认证服务器
> [I] 正在回应用户名请求
> [I] 正在回应密码请求
> [I] 首次认证成功，正在执行 DHCP 脚本以准备第二次认证
> [E] IPv4 地址获取错误
> [W] DHCP 可能尚未完成，将继续等待……
> [I] 认证成功
> [I] DHCP 完成，正在开始第二次认证
> [I] 正在查找认证服务器
> [I] 正在回应用户名请求
> [I] 正在回应密码请求
> [I] 二次认证成功
> [I] 服务器通知：
> [I] 欢迎使用广外大网络！
> [I] 计费通知：
> [I] 您当前使用的服务为default;
> 账户余额为0.00元;
> 计费策略为学生包半年;
> [I] 正定时发送 Keep-Alive 报文以保持在线……
> [I] 认证成功
> ```
> 但是在网络——接口处用`miniEAP客户端`处验证会显示
> `Sun Mar 27 15:18:06 2022 daemon.notice netifd: wan (4844): minieap: Missing username or password.`
> 我再检查下自己编译有没问题
> 
> 

这不是编译问题，
新建的接口`eap`没有配置用户名与密码吧，检查一下。

**Comment by jimlee2048** [comment]
> openwrt上使用的简易指南
> - 安装/编译时添加 [openwrt-minieap-gdufs](https://github.com/jimlee2002/openwrt-minieap-gdufs) 与 [luci-proto-minieap](https://github.com/ysc3839/luci-proto-minieap)
> - 前往Openwrt管理面板，在网络设置中新建接口，协议选择`MiniEAP 客户端`，名字随意（下以eap为例）
> - 进入新建的接口`eap`，配置以下参数
>     - 基本信息中，填写用户名与密码，数据包插件选择rjv3
>     - rjv3插件设置中，EAP广播地址选择`锐捷私有`，DHCP认证选择`二次认证`，其他选项留空即可（已配置默认参数）
>     - 接口物理设置中，选择wan口所在的以太网适配器
> 
> 保存后就可以试着手动连接一下接口，然后去内核日志里看详细日志能不能认证上

如果你忘了如何设置，注意是**新建一个接口**。

**Comment by babattata-ta** [comment]
> > openwrt上使用的简易指南
> > 
> > * 安装/编译时添加 [openwrt-minieap-gdufs](https://github.com/jimlee2002/openwrt-minieap-gdufs) 与 [luci-proto-minieap](https://github.com/ysc3839/luci-proto-minieap)
> > * 前往Openwrt管理面板，在网络设置中新建接口，协议选择`MiniEAP 客户端`，名字随意（下以eap为例）
> > * 进入新建的接口`eap`，配置以下参数
> >   
> >   * 基本信息中，填写用户名与密码，数据包插件选择rjv3
> >   * rjv3插件设置中，EAP广播地址选择`锐捷私有`，DHCP认证选择`二次认证`，其他选项留空即可（已配置默认参数）
> >   * 接口物理设置中，选择wan口所在的以太网适配器
> > 
> > 保存后就可以试着手动连接一下接口，然后去内核日志里看详细日志能不能认证上
> 
> 如果你忘了如何设置，注意是**新建一个接口**。

已经尝试，失败

解决方法是在启动项中添加了
`minieap -u 用户名 -p 密码 -n wan --module rjv3  --service default`
然后在计划任务中添加
`10 6 * * * sleep 70 && touch /etc/banner && reboot`
目前暂时顺利

折腾三天了，非计科类专业的小白感谢大佬的帮助
