### ISSUE TITLE
能看一下12栋的申请者和验证者之间的包吗

### ISSUE THREAD

**Issue by FrenkyOHOHOH** [jimlee2048/minieap-gdufs#3]
你好，我是现在住在南苑13的在校生，我想对比一下十二、十三栋的包有什么区别，能看一下12栋linux下认证抓包的pcap文件吗，想看一下request有没有区别，我的邮箱是frenkyxy0246@gmail.com，如果看到可以回复一下，谢谢

**Comment by jimlee2048** [comment]
你好，已发送邮件，请查收。
感谢帮忙！
